### ISSUE TITLE
CSS编写规范

### ISSUE THREAD

**Issue by Roe-Tian** [Roe-Tian/Front-End-Standard#3]
## 编码声明
- 为了避免内容乱码，统一使用 UTF-8 编码保存
- 样式文件第一行设置字符集为 UTF-8
``` css
@charset "UTF-8"; /* 注意字符集说明应在第一行 */
```

## 命名
一律小写，使用 `-` 连接符
``` css
/*不推荐*/
.gameHeader{}

/*推荐*/
.game-header{}
```

## 选择器
1. 尽量使用 **类选择器**，尽量不要使用 **id选择器** 、**标签选择器** 等
2. 尽量使用 **单一选择器**
3. **选择器层级** 最好不要超过 **3** 层
``` css
/*不推荐*/
#foo-header {}
div {}

/*推荐*/
.foo-header {}
```
``` css
/*不推荐*/
.foo-header .foo-header-nav

/*推荐*/
.foo-header-nav
```

## 属性简写
``` css
/*不推荐*/
.foo{
    padding-top: 2px; 
    padding-bottom: 4px; 
    padding-left: 3px; 
    font-family: 'microsoft yahei';
    font-size: 12px;
    font-weight: normal;
    line-height: 2em;
}  

/*推荐*/
.foo{
    padding: 2px 0 4px 3px;
    font: normal 12px/2em 'microsoft yahei';
}
```

## 属性顺序
CSS 属性顺序是 CSS 良好编码风格的一部分，有助于提高代码可读性，便于发现代码问题，有利于团队合作。

尽量建议使用下列顺序进行书写
1. 定位属性（position、display、float、left、right）
2. 尺寸属性（width、height、padding、margin、border）
3. 字体属性（color、font、text-align）
4. 其他属性（background、cursor、outline）

## 注释
- 注释内容前后各一个空格字符 ` /* 内容 */ `

- 注：在 sass 和 less 等预处理语言上也可以使用双斜线注释，但编译后注释内容不会出现在 css 文件中，所以建议统一使用/* */注释。

- 模块注释，建议 第一行填写描述，最后一行填写分割线
``` css
/* 推荐的模块注释
---------------------------------------------------- */

/* 不推荐的模块注释 ---------------------------------------------------- */
```

## 协议
对资源的引用，需要指定具体域名时，http 或 https协议的，可以不需要具体指定

原因：http 与 https 之间的转换便捷

``` css
/*不推荐*/
.example {
    background: url(http://static.example.com/images/bg.jpg);
}

/*推荐*/
.example {
    background: url(//static.example.com/images/bg.jpg);
}
```
